### PR TITLE
Refactor Docker/Compose

### PR DESCRIPTION
**Pull request by Murazaki**
From @jippi PR in upstream : https://github.com/pixelfed/pixelfed/pull/4844

I had to squash for convenience (110 commits ?) and rebase on latest.

(If there's any concern on using latest staging please reply and tell me why)

### CODE REVIEW

**Comment by Murazaki** [comment]
@jippi any reason for building with bullseye and 8.1 ?

**Comment by jippi** [comment]
it was the baseline for existing Dockerfile, so I just kept it

**Comment by Murazaki** [comment]
Testing on a standard migration case, my observations:

- the acquire-lock can block both the app and worker, and can be left locked on kill
- some ok situations blocks the scripts

```
worker-1  | [entrypoint / 11-first-time-setup.sh] - 👷 Running [php artisan passport:keys] as [www-data]
worker-1  | [entrypoint / 11-first-time-setup.sh] - (stdout) Encryption keys already exist. Use the --force option to overwrite them.
worker-1  | [entrypoint / 11-first-time-setup.sh] - ERROR - ❌ Error!
```

**Comment by Murazaki** [comment]
@jippi trying something on lock file but still not satisfactory :

```bash
# @description Best effort file lock to ensure *something* is not running in multiple containers.
#   The script uses "trap" to clean up after itself if the script crashes
# @arg $1 string The lock identifier
function acquire-lock() {
    local name="${1:-$script_name}"
    local file="${docker_locks_path}/${name}"
    local lock_fd

    ensure-directory-exists "$(dirname "${file}")"

    exec {lock_fd}>"$file"

    log-info "🔑 Trying to acquire lock: ${file}: "
    while !(flock --timeout 0 -x "$lock_fd"); do
        log-info "🔒 Waiting on lock ${file}"

        staggered-sleep
    done

    # not needed but does verify ownership
    stream-prefix-command-output touch "${file}"

    log-info "🔐 Lock acquired [${file}]"

    on-trap "release-lock ${name} ${lock_fd}" EXIT INT QUIT TERM
}

# @description Release a lock aquired by [acquire-lock]
# @arg $1 string The lock identifier
function release-lock() {
    local name="${1:-$script_name}"
    local file="${docker_locks_path}/${name}"
    local lock_fd="$2"

    log-info "🔓 Releasing lock [${file}]"

    exec {lock_fd}>&-
    # Not sure if we should delete then
    stream-prefix-command-output rm -fv "${file}"
}
```

**Comment by Murazaki** [comment]
file lock broke shellcheck, but the CI passed. oh well.

**Comment by jippi** [comment]
flock does not work at all/well between containers due to how it works

I plan to add a "timeout" to "wait" X time (maybe 60s or something) so if it does deadlock (only seen this happen when ctrl+c'ing containers that have a lock during startup)

**Comment by jippi** [comment]
Also, any issues in 11-first-time-setup.sh is [documented in the migration guide](https://jippi.github.io/pixelfed-docs-next/pr-preview/pr-1/running-pixelfed/docker/migrate/v2.0.html) :)

**Comment by Murazaki** [comment]
Thanks.  BTW docs is pushed here too : pixelfed-glitch.github.io/docs

**Comment by jippi** [comment]
Cool - I'm only working on the upstream part of it to pixelfed/pixelfed atm :)

**Pull request merged**
